### ISSUE TITLE
Make login background animated.

### ISSUE THREAD

**Issue by tomeczeklmaodev** [Feedrum-Project/feedrum-design#1]
Login screen looks very static, an animated background would make it look way better.

**Comment by MrMiquy** [comment]
> Login screen looks very static, an animated background would make it look way better.

Dzień dobry, przepraszam za długą odpowiedź. Dziękuję za Twoją ofertę. Pomyślimy o tym.
Hi, sorry for the long answer. Thank you for your offer. We'll think about it.
